[alembic]
script_location = migrations
sqlalchemy.url = sqlite:///tistory_automation.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys =

[formatters]
keys =

[logger_root]
level = WARN
handlers =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic
